services:
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    networks:
      dns_network:
        ipv4_address: 172.20.0.2
    volumes:
      - ./unbound-data:/opt/unbound/etc/unbound

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    depends_on:
      - unbound
    cap_add:
      - SYS_NICE
      - SYS_TIME
    environment:
      TZ: ${TZ}
      FTLCONF_webserver_api_password: ${PIHOLE_WEBPASSWORD}
      FTLCONF_dns_listeningMode: 'all'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    volumes:
      - ./pihole-data/etc-pihole:/etc/pihole
      - ./pihole-data/etc-dnsmasq.d:/etc/dnsmasq.d
    networks:
      dns_network:

networks:
  dns_network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
